apiVersion: v1
kind: ConfigMap
metadata:
  name: "config"
data:
  injector.yaml: |
    initContainerImage:
      registry: docker.io
      repository: dragonflyoss/client
      tag: latest
      digest: ''
      pullPolicy: IfNotPresent
      pullSecrets: []
    unixSockPath: /var/run/dragonfly/dfdaemon.sock
